# Generated by Django 3.1.7 on 2021-03-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=120, null=True)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('is_a_dangerous_good', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('date_of_arrival', models.DateTimeField()),
                ('is_recieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=12, null=True)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('rev_number', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Customer'), (1, 'Supplier'), (2, 'Loader')], default=0)),
                ('location', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('is_paid_or_cleared', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_hub_platform_app.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_hub_platform_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_hub_platform_app.profile')),
            ],
        ),
    ]
